CONFIG_ZMK_USB_LOGGING=n
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000
CONFIG_ZMK_IDLE_TIMEOUT= 30000

# Keeb's Name
CONFIG_ZMK_KEYBOARD_NAME="Shash's Totem"

# Passkey Entry support
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y
